[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "IVDC Club"
authors = [{name = "IVDC Club", email = "ivdc@iiti.ac.in"}]
dynamic = ["version", "description"]
